# Generated by Django 5.1.7 on 2025-03-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_address_user_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='contact_person',
            new_name='business_name',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
