# Generated by Django 5.1.7 on 2025-05-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payout_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', help_text='Whether vendor has been paid', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee taken by platform', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_payout',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be paid to vendor after sale', max_digits=12, null=True),
        ),
    ]
